version: '3'

services:
  # Postgres database
  test-postgres-compose:
    image: postgres
    restart: always
    environment:
      POSTGRES_DATABASE: "postgres"
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "123456!"
    ports:
      - "15432:5432"
    volumes:
      - dbdata:/var/lib/postgres/
    networks:
      - app-network

  # phppgadmin to database interface management
  test-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "support@talkip.com.br"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    ports:
      - "16543:80"
    depends_on:
      - test-postgres-compose
    networks:
      - app-network

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
#    env_file:
#      - .env
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
#      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
