version: '3'

services:
  test-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123456!"
    ports:
      - "15432:5432"
    volumes:
      - ./postgres/data
    networks:
      - postgres-compose-network

  test-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "support@talkip.com.br"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    ports:
      - "16543:80"
    depends_on:
      - test-postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
